name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Rust fmt
      run: |
        shopt -s globstar
        rustfmt **/*.rs --check
  contracts-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-contracts-${{ hashFiles('**/Cargo.lock') }}
    - name: Build creusot-contracts with nightly rustc
      run: cargo build -p creusot-contracts -F nightly
      env:
        RUSTFLAGS: -D warnings
  contracts-build-stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-contracts-stable-${{ hashFiles('Cargo.lock') }}
    - name: Build creusot-contracts with stable rustc
      run: cargo +stable build -p creusot-contracts
      env:
        RUSTFLAGS: -D warnings
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo build
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
    - run: cargo test --test why3 dummy-dummy-dummy # make sure its deps are in the cargo cache
  erasure-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache Cargo build
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
    - name: Get rust-src
      run: rustup component add rust-src
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --test ui -- --erasure-check
  why3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ github.event.pull_request.commits }}
    - name: Fetch target branch
      if: github.base_ref
      run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
    - name: Cache Cargo build
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Cache Opam switch
      uses: actions/cache/restore@v4 # This cache is saved by the install job
      with:
        path: ~/.local/share/creusot/_opam
        key: ${{ runner.os }}-opam-${{ hashFiles('creusot-deps.opam') }}
        restore-keys: ${{ runner.os }}-opam-
    - name: Get current date
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Restore Why3find cache
      uses: actions/cache/restore@v4
      with:
        path: target/.why3find
        key: ${{ runner.os }}-why3find-${{ env.TODAY }}-
    - name: Setup environment
      run: |
        sudo apt update && sudo apt install opam libzmq3-dev
        opam init --bare
        opam --cli=2.1 var --global in-creusot-ci=true
    - name: Install solvers
      # Use only 2 parallel provers, because more provers (4) makes replaying proofs unstable
      run: |
        ./INSTALL --skip-cargo-creusot --skip-creusot-rustc
        cargo run --bin cargo-creusot creusot why3-conf --provers-parallelism 2
        echo -e "\n>> ~/.config/creusot/why3.conf:\n"
        cat ~/.config/creusot/why3.conf
    - run: cargo test --test why3
    - name: Save Why3find cache
      uses: actions/cache/save@v4
      with:
        path: target/.why3find
        key: ${{ runner.os }}-why3find-${{ env.TODAY }}-${{ hashFiles('target/.why3find/**') }}
  install:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - run: rustup update
      if: matrix.os == 'macos-latest'
    - name: Cache Cargo build
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Cache Cargo build
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock', 'prelude-generator/**') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Cache Opam switch
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v4
      with:
        path: ~/.local/share/creusot/_opam
        key: ${{ runner.os }}-opam-${{ hashFiles('creusot-deps.opam') }}
        restore-keys: ${{ runner.os }}-opam-
    - name: Cache Opam switch (MacOS)
      if: matrix.os == 'macos-latest'
      uses: actions/cache@v4
      with:
        path: ~/.creusot/_opam
        key: ${{ runner.os }}-opam-${{ hashFiles('creusot-deps.opam') }}
        restore-keys: ${{ runner.os }}-opam-
    - run: sudo apt update && sudo apt install opam libzmq3-dev
      if: matrix.os == 'ubuntu-latest'
    - run: brew update && brew install opam autoconf zeromq zlib
      if: matrix.os == 'macos-latest'
    - name: setup opam
      run: |
        opam init --bare
        opam --cli=2.1 var --global in-creusot-ci=true
    - run: ./INSTALL
    - name: test cargo creusot new
      run: |
        set -x
        cd ..
        cargo creusot new test-project --main --creusot-contracts ../creusot/creusot-contracts
        cd test-project
        cargo fmt --check
        cargo build
        cargo creusot
        cargo creusot prove
      env:
        RUSTFLAGS: -D warnings
    - name: Minimize Opam cache
      run: opam clean --all-switches --download-cache --logs --repo-cache
